### ISSUE TITLE
GNU make / GCC / Linux build issues

### ISSUE THREAD

**Issue by REMqb** [DigitalPulseSoftware/Erewhon-Game#2]
1) ~~/!\ Case sensitive paths~~
2) The sdk include path isn't provided to GCC
3) The library search path provided to ld is `NazaraEngine/bin/...` whereas the default build path is `NazaraEngine/lib/...`

**Comment by DrLynix** [comment]
It looks like you forgot to `package` Nazara before using it, run `./premake5-linux64 package` command and you'll have a new `package` folder containing everything like the build system of Utopia excepts it.
